[package]
name = "proxy-vouch"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "A desktop proxy checker with clear, verifiable results"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-clipboard-manager = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
proxy-vouch-core = { path = "../crates/core" }
